language: python
python:
  - "2.6"
  - "2.7"
before_install:
  # install NumPy dependencies
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libatlas-base-dev
  - sudo apt-get install -qq python-numpy
install:
  - python setup.py install
script:
  - nosetests tests